config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  root to: 'pages#home'
  get 'project', to: 'pages#project'
  get 'team', to: 'pages#team'
  get 'why', to: 'pages#why'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/interview.rb
class Interview < ApplicationRecord
  validates :first_name, presence: true, uniqueness: true
  validates :last_name, presence: true, uniqueness: true
  validates :language, presence: true
  validates :category, presence: true
  belongs_to :stage

  mount_uploader :photo, PhotoUploader
  mount_uploader :video, VideoUploader
end

app/models/stage.rb
class Stage < ApplicationRecord
  has_many :interviews
  validates :area, presence: true
  validates :date, presence: true
  validates :country, presence: true
  validates :city, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :project, :why, :team ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <script src="https://use.typekit.net/fpr1xcx.js"></script>
    <script>try{Typekit.load({ async: true });}catch(e){}</script>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- <div class="banner" style="background-image: linear-gradient(-225deg, rgba(70,232,40,0.1) 0%, rgba(70,232,40,0.2) 50%), url(http://res.cloudinary.com/dkzfps9zm/image/upload/v1496586023/Inspirher/escaladeoriginale_lsaqye.jpg);"> -->
  <div class="home-box">
    <div class="home-box-content text-center">
        <h3>Inspir'her</h3>
        <p>Encourage young girls to dare...find out more about our project</p>
        <%= link_to "MORE", why_path, class: "home-btn-more" %>
    </div>
    <%= link_to "", why_path, class: "home-box-link" %>
  </div>
<!-- </div> -->

app/views/pages/project.html.erb
<p> Notre projet consiste à réaliser une mosaïque de portraits de femmes inspirantes. Pour cela, nous allons partir à leur rencontre en traversant l'Europe à vélo. Le but ? mettre en lumière les facteurs de réussite chez les femmes, et de faire de ces femmes entrepreneurs, sportives de haut niveau, journalistes ou femmes politiques des <strong>modèles d'inspiration</strong>.</p>

<!-- vidéo -->

app/views/pages/team.html.erb
<div class="full_image">
  <%= cl_image_tag("IMG_6936_dzabqv.jpg", width: 1291, height: 450, crop: :fill) %>
  <h1>L'équipe</h1>
</div>

<div class="content text-justify">
  <h3>Qui sommes-nous ?</h3>
  <p>Ce qui nous rassemble ? Notre <strong>énergie</strong>, notre <strong>ambition</strong>, notre goût de l’effort, notre optimisme et notre soif de découvrir, rencontrer, voyager, mais aussi et surtout notre envie de <strong>porter et partager un projet qui a du sens</strong>.</p>

  <p>Ce sont nos échanges et réflexions sur nos ambitions professionnelles respectives qui ont fait naître <strong>Inspir’her</strong> : comment au 21e siècle, trois étudiantes en Grande Ecole peuvent-elles être encore être si peu sûres de leurs ambitions professionnelles ? Nous souhaitons choisir un métier qui ait du sens, sommes passionnées d’entreprenariat et de Social Business, sommes persuadées de notre capacité à mener de front vie professionnelle et vie personnelle, aimons la tech’ et le sport, souhaitons avoir des responsabilités, nous écartons des parcours tout tracés…mais comme beaucoup, nous avons encore bien du mal à nous projeter. Toutes trois avons eu la chance de grandir avec l’idée que « quand on veut, on peut »…mais c'est toujours plus facile en ayant des modèles en tête.</p>

  <p>Pour nous, <strong>Inspir’her</strong> c’est donc <strong>à la fois un défi et une évidence</strong>. Un défi parce que notre projet implique de dépasser des limites culturelles, sportives, ou personnelles ; une évidence, parce que nous manquons encore de modèles féminins, que les inégalités Hommes / Femmes sont encore trop grandes et que nous sommes persuadées que celles-ci ne peuvent se réduire qu’en donnant encore plus d’ambition aux filles et aux femmes.</p>

  <p>Nous, trois jeunes étudiantes d’<strong>HEC Paris</strong>, allons donc parcourir un petit bout du monde pour rencontrer des femmes et leur entourage, afin que nous puissions tous nous en inspir’her.</p>

  <h3>Cécile, Alix et Charlène en quelques mots :</h3>

  <p>Curieuse et enthousiaste,<strong>Cécile</strong> est toujours à la recherche de nouveauté. Passionnée d'innovations techno et de social business, elle a fait deux stages en start-up à Paris avant de travailler à New Delhi. <strong>Inspir’her</strong>  lui permettra de découvrir, au-delà des parcours féminins inspirants, des modèles d'entreprises innovantes à l'étranger.</p>

  <p>Déterminée et curieuse,<strong>Alix</strong> s'est toujours demandé si elle avait ou non un rôle particulier à jouer en tant que femme, notamment dans sa carrière professionnelle. Convaincue de la nécessité de partir à l'international pour s'inspirer de ce qu'il s'y fait, elle attend avec impatience l'aventure <strong>Inspir’her</strong> !</p>

  <p>Sportive invétérée, passionnée de relations humaines et des échanges culturels, strongCharlène est admirative des aventures entrepreneuriales, en France et à l'étranger. Pour cette Franco-Polonaise, <strong>Inspir'her</strong> c'est l'occasion de rencontrer des femmes qui peuvent lui servir de modèle et d'en faire profiter le plus grand nombre.</p>
</div>

app/views/pages/why.html.erb
<div class="full_image">
  <%= cl_image_tag("girlpower_n71ovs.jpg", width: 1291, height: 450, crop: :fill) %>
  <h1> Pourquoi ?</h1>
</div>

<div class="content text-justify">

  <div class="blockquote">
    <div class="quote">
      <p>"We need women role models everywhere. I think that it is really hard to imagine yourself as something you don't see."</p>
    </div>
    <div class="author">
      <p>-Chelsea Clinton</p>
    </div>
  </div>


  <h3> Notre constat ? Un manque d'initiatives féminines </h3>

  <p> On ne compte plus les études, chiffres et articles qui mettent en avant les différences hommes / femmes. Ces chiffres nous les connaissons tous, et pourtant...<p>
  <p><strong>...les femmes continuent à oser moins, et évitent de se mettre en avant.</strong><p>
  <p>Afin que les femmes dépassent leurs propres barrières, nous avons décidé de les faire ré-<strong>agir</strong> !</p>

  <h3> Notre défi? Encourager les jeunes femmes à se lancer, entreprendre et oser! </h3>

  <p> Convaincues de la force des rôles modèles féminins, et face à leur manque de visibilité, nous avons décidé d’aller à la rencontre de femmes aux parcours variés et inspirants.</p>
  <p> En diffusant leurs témoignages, nous souhaitons susciter chez les filles l'envie de se projeter et d’oser. C’est une façon pour nous de leur dire <strong>“Regarde, elle l’a fait, pourquoi pas toi ?”</strong></p>

  <h3> Notre méthodologie ? Rencontrer, Comprendre, Inspirer, Agir </h3>
</div>
  <div class="wrapper text-justify">
    <div class="container">
      <div class="row">
        <div class="col-sm-4">
          <p class= "text-center"> Rencontrer, Comprendre </p>
          <p> Nous échangeons avec des femmes aux profils, aux histoires, aux carrières variés. Entrepreneuses, sportives, chercheuses…</p>
        </div>
        <div class="col-sm-4">
          <p class= "text-center"> Inspirer </p>
          <p> Notre slogan au cours de cette aventure ! Nous présenterons une mosaïque de parcours féminins variés. Grâce à des interviews, nous rendons accessibles à toutes et à tous des exemples de femmes inspirantes.</p>
        </div>
        <div class="col-sm-4">
          <p class= "text-center" > Agir </p>
          <p> Nous souhaitons définir les facteurs de succès des femmes d’inspiration. Nous partagerons les portraits de ces femmes lors de conférences dans des écoles, des universités ou des entreprises.</p>
        </div>
      </div>
    </div>
  </div>


<!-- <h6> Et le vélo dans tout ça ?!</h6>
<p> Deux principales idées nous ont convaincues de faire du vélo notre moyen de transport pour notre périple :</p> -->

<!-- <ul>
  <li> <strong>Un vecteur d'émancipation de la femme :</strong> On l'oublie trop souvent, mais le vélo a bouleversé la vie des femmes ! Il leur a permis de troquer leurs robes pour des pantalons, de gagner en indépendance et liberté... Nous avons ainsi voulu nous appuyer sur ce symbole pour mettre en valeur des femmes.</li>
  <li><strong>Un challenge sportif :</strong>Nous allons aller à la rencontre de femmes qui ont des projets de vie qui dépassent et surpassent toutes les attentes... Pour aller dans leur sens, et donner un maximum de cohérence à nos ambitions d'inspiration, nous avons voulu définir un projet qui nous pousse nous aussi à repousser nos limites.</li>
</ul> -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="navbar-wagon-left">
    <%= cl_image_tag("Logocourtv1_s6kgev.png", width: 70, height: 70, crop: :fill) %>
    <%= link_to "INSPIR'HER", root_path , class: "title"%>
  </div>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <div class="dropdown">
      <%= link_to "NOTRE PROJET", "#",class: "navbar-wagon-item navbar-wagon-link dropdown-toggle", "data-toggle" => "dropdown" %>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="project.html">LE PROJET</a></li>
        <li><a href="why.html">POURQUOI ?</a></li>
        <li><a href="team.html">L'EQUIPE</a></li>
      </ul>
    </div>
    <div class="dropdown">
      <%= link_to "PORTRAITS DE FEMMES", "#",class: "navbar-wagon-item navbar-wagon-link dropdown-toggle", "data-toggle" => "dropdown"%>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="project.html">TOUS</a></li>
        <li><a href="why.html">PAR CATEGORIES</a></li>
        <li><a href="team.html">PAR PAYS</a></li>
      </ul>
    </div>
    <div class="dropdown">
      <%= link_to "LE PARCOURS", "#",class: "navbar-wagon-item navbar-wagon-link dropdown-toggle", "data-toggle" => "dropdown"%>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="project.html">ITINERAIRE</a></li>
        <li><a href="why.html">EUROPE DU SUD</a></li>
        <li><a href="team.html">EUROPE DE L'EST</a></li>
        <li><a href="team.html">EUROPE DE L'OUEST</a></li>
      </ul>
    </div>
    <%= link_to "CONTACT", "#",class: "navbar-wagon-item navbar-wagon-link"%>
  </div>
</div>

<!-- Profile picture and dropdown -->
<!-- Dropdown list appearing on mobile only -->